
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

name: Asymptotic Testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run asymptotic testing
        uses: SiyaoIsHiding/r-asymptotic-testing@v1

  
