
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

name: Asymptotic Testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run asymptotic testing
        uses: SiyaoIsHiding/r-asymptotic-testing@v1

  
